---
Resources:
  EBSVolumeKMSKeyAlias: alias/aoc-EBSVolume-KMS
  DynamoDBKMSKeyAlias: alias/aoc-DynamoDB-KMS
  LambdaKMSKeyAlias: alias/aoc-Lambda-KMS
  S3KMSKeyAlias: alias/aoc-S3-KMS
  SNSKMSKeyAlias: alias/aoc-SNS-KMS