---
- name: Create kms key ids configuration tasks
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    - name: Ensure stage directory exists
      file: path=../../../stage/user-config/ state=directory

    - name: Create Packer AEM and Stack Builder KMS Key IDs configuration file
      create_kms_key_ids_config:
        template_dir: '../../../templates/cloudformation/aws-resources.yaml'
        region: "{{ aws.region }}"
        ebs_key_alias: "{{ Resources.EBSVolumeKMSKeyAlias }}"
        dynamodb_key_alias: "{{ Resources.DynamoDBKMSKeyAlias }}"
        lambda_key_alias: "{{ Resources.LambdaKMSKeyAlias }}"
        s3_key_alias: "{{ Resources.S3KMSKeyAlias }}"
        sns_key_alias: "{{ Resources.SNSKMSKeyAlias }}"
        out_file_packer: "../../../stage/user-config/packer-kms-key-ids.yaml"
        out_file_stack_builder : "../../../stage/user-config/stack-builder-kms-key-ids.yaml"

