---
AWSTemplateFormatVersion: "2010-09-09"
Conditions:
  ArtifactsBucketCondition:
    Fn::Equals:
      - Ref: CreateArtifactsBucketParameter
      - "True"

Description: Create user AWS resources
Parameters:
  StackPrefixParameter:
    Description: Stack Prefix for Forward Proxy stack
    Type: String
  VPCIdParameter:
    Description: VPC ID
    Type: String
  CreateArtifactsBucketParameter:
    Description: Toggle creating an S3 Bucket for storing dev team's artifacts (true/false)
    Type: String
  ArtifactsBucketNameParameter:
    Type: String
    Description: Name of the S3 Bucket where the artifacts are to be stored
  Route53PublicHostedZoneNameParameter:
    Description: Route53 Public Hosted Zone Name the public Record Set will be created in
    Type: String
  AemOpenCloudRoute53PrivateHostedZoneNameParameter:
    Description: AEM OpenCloud Route53 Private Hosted Zone Name the private Record Set will be created in
    Type: String
  InfraCatalogRoute53PrivateHostedZoneNameParameter:
    Description: Infra Catalog Route53 Private Hosted Zone Name the private Record Set will be created in
    Type: String
  CorpNetworkCidrParameter:
    Description: IPv4 CIDR of corp network
    Type: String

Resources:

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Condition: ArtifactsBucketCondition
    Properties:
      BucketName:
        Ref: ArtifactsBucketNameParameter
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CorpNetworkSecurityGroup:
    Properties:
      GroupDescription: Corp Network Security Group
      Tags:
        - Key: Name
          Value: Corp Network Security Group
        - Key: StackPrefix
          Value:
            Ref: StackPrefixParameter
      VpcId:
        Ref: VPCIdParameter
    Type: AWS::EC2::SecurityGroup
  CorpNetworkSecurityGroupIngress0:
    Properties:
      CidrIp:
        Ref: CorpNetworkCidrParameter
      FromPort: '22'
      GroupId:
        Ref: CorpNetworkSecurityGroup
      IpProtocol: tcp
      ToPort: '22'
    Type: AWS::EC2::SecurityGroupIngress

  ForwardProxyRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: InfraCatalogRoute53PrivateHostedZoneNameParameter
      Name:
        Fn::Sub: forward-proxy.${InfraCatalogRoute53PrivateHostedZoneNameParameter}
      ResourceRecords:
        - 'shinesolutions.com'
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet

  Demo1ConsolidatedRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53PublicHostedZoneNameParameter
      Name:
        Fn::Sub: demo1-con.${Route53PublicHostedZoneNameParameter}
      ResourceRecords:
        - 'shinesolutions.com'
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet

  Demo1AuthConsolidatedRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53PublicHostedZoneNameParameter
      Name:
        Fn::Sub: auth.demo1-con.${Route53PublicHostedZoneNameParameter}
      ResourceRecords:
        - 'shinesolutions.com'
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet

  Demo1PubConsolidatedRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53PublicHostedZoneNameParameter
      Name:
        Fn::Sub: pub.demo1-con.${Route53PublicHostedZoneNameParameter}
      ResourceRecords:
        - 'shinesolutions.com'
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet

  Demo1FullSetRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53PublicHostedZoneNameParameter
      Name:
        Fn::Sub: demo1-fs.${Route53PublicHostedZoneNameParameter}
      ResourceRecords:
        - 'shinesolutions.com'
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet

  Demo1AuthFullSetRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53PublicHostedZoneNameParameter
      Name:
        Fn::Sub: auth.demo1-fs.${Route53PublicHostedZoneNameParameter}
      ResourceRecords:
        - 'shinesolutions.com'
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet
