---
AWSTemplateFormatVersion: "2010-09-09"
Description: Manage EBS Volume encryption CMK
Parameters:
  ShareCMKToAWSAccount:
    Type: String
    Description: AWS Account ID to share the CMK to.
    Default: 1234567890
Outputs:
  KMSKKeyID:
    Description: The  EBS Volume Key ARN
    Export:
      Name: KMSKKeyID
    Value: !Ref KMSKKey
Resources:
  KMSKKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key for  EBS Volume encryption.
      Enabled: True
      EnableKeyRotation: True
      PendingWindowInDays: 30
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Deny Key Deletion for all'
            Effect: Deny
            Principal:
              AWS: '*'
            Action:
              - 'kms:ScheduleKeyDeletion'
              - 'kms:Delete*'
            Resource: '*'
          - Sid: 'Allow access for Key Administrators'
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:Get*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Tag*'
              - 'kms:Update*'
              - 'kms:Untag*'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: 'Allow usage of the Key in different AWS Accounts'
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${ShareCMKToAWSAccount}:root'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: 'Allow attachment of persistent resources in different AWS Accounts'
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${ShareCMKToAWSAccount}:root'
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
          - Sid: 'Allow use of the key'
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: 'Allow attachment of persistent resources'
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling'
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: true
  KMSKKeyAlias:
    DependsOn:
      - KMSKKey
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/EBS-KMS
      TargetKeyId: !Ref KMSKKey
